### ISSUE TITLE
This package cannot be safely installed by EasyInstall: SandboxViolation

### ISSUE THREAD

**Issue by blshkv** [twisted/klein#186]
```
klein-17.2.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                [ ok ]
 * checking ebuild checksums ;-) ...                                                                                       [ ok ]
>>> Unpacking source...
>>> Unpacking klein-17.2.0.tar.gz to /var/tmp/portage/dev-python/klein-17.2.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/klein-17.2.0/work
>>> Preparing source in /var/tmp/portage/dev-python/klein-17.2.0/work/klein-17.2.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/klein-17.2.0/work/klein-17.2.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/klein-17.2.0/work/klein-17.2.0 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
no previously-included directories found matching '.travis'
no previously-included directories found matching 'tests'
warning: no previously-included files found matching 'examplesetup.py'
no previously-included directories found matching 'src/exampleproj'
no previously-included directories found matching 'src/incremental/newsfragments'
Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    maintainer_email='hawkowl@twistedmatrix.com',
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 317, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/usr/lib64/python2.7/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/easy_install.py", line 1108, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('/var/tmp/portage/dev-python/klein-17.2.0/work/klein-17.2.0-python2_7/lib/incremental', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

```

**Comment by blshkv** [comment]
sorry, looks like it is a false positive. I have installed ```incremental``` and the message is gone.

**Comment by glyph** [comment]
*Please* do not use `easy_install`.  Use `pip`.

**Comment by blshkv** [comment]
I'm not using either of them. I'm packaging klein for Gentoo which uses a standard ```https://pypi.python.org/pypi/setuptools```

**Comment by glyph** [comment]
Paging @dstufft to the thread: is this a safe usage of `EasyInstall` stuff, given a relatively modern setuptools?

**Comment by dstufft** [comment]
Um, it looks like it's just Gentoo calling ``python setup.py build`` and some interaction with ``setup_requires`` and something Gentoo has done. I wouldn't worry about it since Gentoo is likely going to want to manage the ``setup_requires`` themselves anyways.

**Comment by glyph** [comment]
Thanks for looking; in that case I will happily ignore this :).

**Comment by mr-wakadoodle** [comment]
> sorry, looks like it is a false positive. I have installed `incremental` and the message is gone.

can you tell step by step please on how to solve this situation

**Comment by blshkv** [comment]
@mr-wakadoodle Sorry, I don't really remember. Based on my comments, I just had to install all dependencies : https://github.com/twisted/klein/blob/master/setup.py#L28-L38

here is a Gentoo ebuild for the previous version:
```
klein-17.2.0.ebuild 
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

PYTHON_COMPAT=( python2_7 )

inherit distutils-r1

DESCRIPTION="A micro-framework for developing production-ready web services "
HOMEPAGE="https://github.com/twisted/klein"
SRC_URI="mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="test"

RDEPEND="dev-python/werkzeug[${PYTHON_USEDEP}]
        dev-python/six[${PYTHON_USEDEP}]
        dev-python/incremental[${PYTHON_USEDEP}]
        || (
                >=dev-python/twisted-16.0.0[${PYTHON_USEDEP}]
                (       $(python_gen_cond_dep 'dev-python/twisted-names[${PYTHON_USEDEP}]' 'python2_7')
                        $(python_gen_cond_dep 'dev-python/twisted-web[${PYTHON_USEDEP}]' 'python2_7')
                )
        )"

DEPEND="${RDEPEND}"
```
