### ISSUE TITLE
pydal select().as_list() return error

### ISSUE THREAD

**Issue by sugizo** [twisted/klein#430]
**api.py**
```
@app.route('/api/rows_as_list/<tablename>/', methods = ['GET'] )
@app.route('/api/rows_as_list/<tablename>/<rec_id>', methods = ['GET'] )
def rows_as_list(request, tablename, rec_id = None):
    if rec_id and rec_id.isdigit() and int(rec_id) > 0:
        query = (db[tablename]['id'] == rec_id)
    else:
        query = (db[tablename]['id'] > 0)
    rows = db(query).select().as_list()
    return dict(rows = rows)
```

**execute**
```
curl -X GET -i http://localhost:8000/api/rows_as_list/instrument/
curl -X GET -i http://localhost:8000/api/rows_as_list/instrument/1
```

**result**
```
    Traceback (most recent call last):
      File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
        return callWithContext({"system": lp}, func, *args, **kw)
      File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
        return context.call({ILogContext: newCtx}, func, *args, **kw)
      File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
        return func(*args,**kw)
    --- <exception caught here> ---
      File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
        why = getattr(selectable, method)()
      File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/twisted/internet/abstract.py", line 247, in doWrite
        self.dataBuffer = _concatenate(
      File "/Users/sugizo/miniconda3/envs/python3_test/lib/python3.8/site-packages/twisted/internet/abstract.py", line 24, in _concatenate
        return b''.join([memoryview(bObj)[offset:]] + bArray)
    builtins.TypeError: sequence item 9: expected a bytes-like object, dict found
```

**question**
how to achieve it in klein way ?

**n.b.**
- above code use pydal as database abstraction layer
- `db(query).select().as_list()` is pydal syntax and tested work well in another python framework (web2py, py4web, etc)

thanks

**Comment by wsanchez** [comment]
A route handler is expected to return `bytes`, not a `dict`.
