### ISSUE TITLE
klein.test.test_form.TestForms.test_cookieWithToken fails with treq 22.1.0

### ISSUE THREAD

**Issue by exarkun** [twisted/klein#547]
```
[FAIL]
Traceback (most recent call last):
  File "/home/exarkun/VirtualEnvs/scratch/lib/python3.9/site-packages/klein/test/test_form.py", line 763, in test_cookieWithToken
    self.assertEqual(to.calls, [("hello", 1234)])
  File "/home/exarkun/Work/python/twisted/src/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/nix/store/wl02plhc6zf84m6x9984l42wnnnbly5m-python3-3.9.6/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/wl02plhc6zf84m6x9984l42wnnnbly5m-python3-3.9.6/lib/python3.9/unittest/case.py", line 1037, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/nix/store/wl02plhc6zf84m6x9984l42wnnnbly5m-python3-3.9.6/lib/python3.9/unittest/case.py", line 1019, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [] != [('hello', 1234)]

Second list contains 1 additional elements.
First extra element 0:
('hello', 1234)

- []
+ [('hello', 1234)]

klein.test.test_form.TestForms.test_cookieWithToken
```

This is a regression compared to the previous release treq, 21.5.0.

Since treq 22.1.0 includes security-related fixes having to do with cookie handling, maybe the code under test or the test itself not handling cookies properly?

**Comment by twm** [comment]
This appears to be https://github.com/twisted/treq/pull/343 which was fixed in treq 22.2.0, which is what Klein currently tests with. It was a bug in the security fix.
