### ISSUE TITLE
Non-ASCII chars in the path part of an URL raise an UnicodeDecodeError

### ISSUE THREAD

**Issue by hynek** [twisted/klein#61]
ISTM that currently klein will always crash if a non-ASCII URL is called (eg. `localhost/föö`):

```python
from klein import run, route

@route('/')
def hello(request):
    return "Hello"

run("localhost", 8080)
```

If you run `curl 0.0.0.0:8080/fööö` *or* `curl 0.0.0.0:8080/f%C3%B6%C3%B6` you’ll get:

```
* Hostname was NOT found in DNS cache
*   Trying 0.0.0.0...
* Connected to 0.0.0.0 (127.0.0.1) port 8080 (#0)
> HEAD /fööö HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 0.0.0.0:8080
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
HTTP/1.1 500 Internal Server Error
< Date: Fri, 21 Nov 2014 14:21:20 GMT
Date: Fri, 21 Nov 2014 14:21:20 GMT
< Content-Length: 6534
Content-Length: 6534
< Content-Type: text/html
Content-Type: text/html
* Server TwistedWeb/14.0.2 is not blacklisted
< Server: TwistedWeb/14.0.2
```
(in the second case it’s `> HEAD /f%C3%B6%C3%B6 HTTP/1.1` of course)

and this traceback:

```
2014-11-21 15:26:49+0100 [HTTPChannel,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
	    why = self.lineReceived(line)
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/twisted/web/http.py", line 1656, in lineReceived
	    self.allContentReceived()
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/twisted/web/http.py", line 1731, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/twisted/web/http.py", line 827, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
	    self.render(resrc)
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
	    body = resrc.render(self)
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/klein/resource.py", line 73, in render
	    default_method=request.method, url_scheme=url_scheme)
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/werkzeug/routing.py", line 1124, in bind
	    url_scheme, path_info, default_method, query_args)
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/werkzeug/routing.py", line 1235, in __init__
	    self.path_info = to_unicode(path_info)
	  File "/Users/hynek/.virtualenvs/71a275356bff3bc9/lib/python2.7/site-packages/werkzeug/_compat.py", line 202, in to_unicode
	    return x.decode(charset, errors)
	exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
```

**N.B.** Query parameters like `localhost/?föö=bär` work fine.

***

I’ve checked the werkzeug functions and it’s apparent that the only way to fix this, is to fix it in Klein and pass only Unicode strings down to Werkzeug.

Maybe add an option to force certain charset and alternatively use chardet?

**Comment by brighid** [comment]
PR #62 looks like it fixed this: should this still be open?

**Comment by glyph** [comment]
Thanks for noticing, @brighid . I think you're right.
